# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme


# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "fr"
title: Guilde Ensemble
email:
description: "Blog de la Guilde Ensemble"
google_site_verification: Wtqkmdqg5oTlBT3BE3J6DVbnHigkZJrV1FpN-j_-U4Y

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Krades"
  avatar : "/assets/images/Abo.png"
  bio              : ""
  location         : "Dans le monde des Douze"

      
          

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

markdown: kramdown
mathjax: true


gallery:
  - url: /assets/images/W&S/W&S mondocanard marché 1.png
    image_path: /assets/images/W&S/W&S mondocanard marché 1.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"
  - url: /assets/images/W&S/W&S mondocanard marché 2.png
    image_path: /assets/images/W&S/W&S mondocanard marché 2.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"
  - url: /assets/images/W&S/W&S mondocanard marché 3.png
    image_path: /assets/images/W&S/W&S mondocanard marché 3.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"
  - url: /assets/images/W&S/W&S mondocanard marché 4.png
    image_path: /assets/images/W&S/W&S mondocanard marché 4.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"
  - url: /assets/images/W&S/W&S mondocanard marché 5.png
    image_path: /assets/images/W&S/W&S mondocanard marché 5.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"
  - url: /assets/images/W&S/W&S mondocanard marché 6.png
    image_path: /assets/images/W&S/W&S mondocanard marché 6.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"
  - url: /assets/images/W&S/W&S mondocanard marché 7.png
    image_path: /assets/images/W&S/W&S mondocanard marché 7.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"
  - url: /assets/images/W&S/W&S mondocanard marché 8.png
    image_path: /assets/images/W&S/W&S mondocanard marché 8.png
    alt: "Weslh & Shedar - le marché"
    title: "Le marché"

